export const USER_ACTION = {
    SET_USER: 'SET_USER',
    USER_LOGOUT: 'USER_LOGOUT',
    SET_USER_LOADING: 'SET_USER_LOADING',
    ADD_USER_FAVORITE: 'ADD_USER_FAVORITE',
    REMOVE_USER_FAVORITE: 'REMOVE_USER_FAVORITE',
}
