export const CART_ACTION = {
    ADD_CART: 'ADD_CART',
    CLEAN_CART: 'CLEAN_CART',
    DECREASE_QUANTITY: 'DECREASE_QUANTITY',
    INCREASE_QUANTITY: 'INCREASE_QUANTITY',
    DELETE_CART_ITEM: 'DELETE_CART_ITEM',
}
