export const PRODUCT_ACTION = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    START_EDIT: 'START_EDIT',
    CANCEL_EDIT: 'CANCEL_EDIT',
    SET_EDITED_FIELD: 'SET_EDITED_FIELD',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    SET_PRODUCT_LOADING: 'SET_PRODUCT_LOADING', // Процесс загрузки
    SET_PRODUCT_LOADED: 'SET_PRODUCT_LOADED', // Все ли продукты загружены
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    SET_PRODUCT_SEARCH: 'SET_PRODUCT_SEARCH',
}
